name: Commit1024吧

on:
  schedule:
      - cron: '0 */2 * * *'
  # 手动触发一个工作流
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: StartCommit
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python src/tasks/auto_commit.py "1024吧" "227c9_ck_info=%2F%09; ismob=1; PHPSESSID=lagi5bcp0ijqlsfpg22lk168r1; 227c9_winduser=BQRdAwBUOVECVVIFBgYLVFMDAlBUVAMEVAEDUlcFBgNaVVFQUlNcPARWBgZTBQBdAgVfCFcBAAIADFBQAFMNU1UHV1cOVF5U; 227c9_groupid=13; 227c9_lastvisit=0%091643812486%09%2Findex.php%3F" "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1"
    