name: Commit98我日他得

on:
  schedule:
      - cron: '0 */1 * * *'
  # 手动触发一个工作流
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: StartCommit
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python src/tasks/auto_tangtang.py "我日他得" "cPNj_2132_saltkey=Bu7037Pu; cPNj_2132_lastvisit=1673266356; cPNj_2132_lastfp=66abe79b56fe4d1db0defa055279da8b; cPNj_2132_ulastactivity=1673269979%7C0; cPNj_2132_auth=0858XaNm5wUvXEVL%2BC%2FxV58qR9hDLzU5cRqdGwcYFaBD3YsnJkr5qn%2F30vUzR2vYG3v05hFXvFHV%2FpKSzs%2F7I12d%2Blk; cPNj_2132_lastcheckfeed=415015%7C1673269979; cPNj_2132_lip=101.86.157.94%2C1673269979; cPNj_2132_sid=0; cPNj_2132_nofavfid=1; cPNj_2132_home_diymode=1; cPNj_2132_sendmail=1; cPNj_2132_lastact=1673270411%09misc.php%09patch" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    