name: Commit98我要舔你

on:
  schedule:
      - cron: '0 */1 * * *'
  # 手动触发一个工作流
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: StartCommit
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python src/tasks/auto_tangtang.py "我要舔你" "cPNj_2132_saltkey=rOLPzl7d; cPNj_2132_lastvisit=1672626661; cPNj_2132_lastfp=bc56b1f21fc3b458ea72f14c0f3faf3d; cPNj_2132_auth=bd89CyurRPnr%2BfyS6wwSb8rETOF6wScsYmUzyWh5pcljDuqh29BhHG%2FOMEUqKCsiqqw5sSMkrhE1a8kPIQmdNr8o7qU; cPNj_2132_lastcheckfeed=417586%7C1672630317; cPNj_2132_sid=0; cPNj_2132_nofavfid=1; PHPSESSID=d9b8dmf8obt01amb25p60ajjhj; cPNj_2132_home_diymode=1; cPNj_2132_secqaaqSANge0=4656.62d216d3633ea45ba3; cPNj_2132_secqaaqSAJsu0=4663.19b63208593b4beec2; cPNj_2132_ulastactivity=1672650622%7C0; cPNj_2132_lastact=1672650802%09home.php%09spacecp; cPNj_2132_lastact=1672651387%09forum.php%09guide; cPNj_2132_sid=0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
    