name: Commit小妖精的魔人

on:
  schedule:
      - cron: '0 */2 * * *'
  # 手动触发一个工作流
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: StartCommit
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python src/tasks/auto_commit.py "小妖精的魔人" "227c9_ipfrom=8c08bd9a04c5bf622e785230f345f10a%09Unknown; 227c9_postReplyLastData=4821222%B8%D0%D0%BB%B7%D6%CF%ED; ismob=1; PHPSESSID=gqmo2ssolr1anfr0op32ctag57; 227c9_ck_info=%2F%09; 227c9_winduser=AgJRBwdQOQhRVFpWBlBcVVBSBgAGBwFXBVUNBlNQAgBbB1YGDlMHPAJaBQVXVQdQBwUIAQddU1ACUwdVVFIFBVEABw1aUgQB; 227c9_groupid=12; 227c9_lastvisit=0%091643787115%09%2Findex.php%3F" "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1"
    